apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: fastapi-learning
  annotations:
    dev.okteto.com/auto-ingress: "true"

  name: fastapi-learning
spec:
  type: ClusterIP
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: fastapi-learning
status:
  loadBalancer: {}
